/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBreadcrumb: typeof import('./core/components/AppBreadcrumb.vue')['default']
    AppNavbar: typeof import('./core/components/AppNavbar.vue')['default']
    AppSidebar: typeof import('./core/components/AppSidebar.vue')['default']
    AppToastContainer: typeof import('./core/components/AppToastContainer.vue')['default']
    AutoForm: typeof import('./components/AutoForm/AutoForm.vue')['default']
    BaseAlert: typeof import('./components/BaseAlert.vue')['default']
    BaseBadge: typeof import('./components/BaseBadge.vue')['default']
    BaseBottomSheet: typeof import('./components/BaseBottomSheet.vue')['default']
    BaseButton: typeof import('./components/BaseButton.vue')['default']
    BaseCard: typeof import('./components/BaseCard.vue')['default']
    BaseDatePicker: typeof import('./components/BaseDatePicker.vue')['default']
    BaseModal: typeof import('./components/BaseModal.vue')['default']
    BaseTabs: typeof import('./components/BaseTabs.vue')['default']
    DataTable: typeof import('./components/DataTable/DataTable.vue')['default']
    FormField: typeof import('./components/AutoForm/FormField.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarGroup: typeof import('./core/components/SidebarGroup.vue')['default']
    SidebarItem: typeof import('./core/components/SidebarItem.vue')['default']
    StatCard: typeof import('./components/StatCard.vue')['default']
  }
}
